name: CI-CD to EKS with Helm and ArgoCD

on:
  push:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

  docker-build-push:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push Docker Image
        run: |
          IMAGE_TAG=${{ github.sha }}
          ECR_REPO=<AWS_ACCOUNT_ID>.dkr.ecr.<AWS_REGION>.amazonaws.com/<ECR_REPOSITORY_NAME>
          docker build -t $ECR_REPO:$IMAGE_TAG .
          docker push $ECR_REPO:$IMAGE_TAG
          echo "ECR_REPO=$ECR_REPO" >> $GITHUB_ENV
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

  update-helm-chart:
    runs-on: ubuntu-latest
    needs: docker-build-push
    steps:
      - name: Checkout GitOps Repo
        uses: actions/checkout@v3
        with:
          #repository: <YOUR_GITHUB_ORG>/<YOUR_GITOPS_REPO>
           repository: waj310/my-gitops-repo
           path: my-gitops-repo
           ssh-key: ${{ secrets.DEPLOY_KEY }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Helm values.yaml
        run: |
          sed -i "s|repository:.*|repository: $ECR_REPO|" helm/values.yaml
          sed -i "s|tag:.*|tag: $IMAGE_TAG|" helm/values.yaml

      - name: Commit & Push Changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git commit -am "Update image to $IMAGE_TAG"
          git push

